-- Paese esplicito sullo snapshot BSR (storeKey resta il marketplaceId Amazon).
ALTER TABLE "product"."StoreBsrSnapshot" ADD COLUMN "countryCode" TEXT NOT NULL DEFAULT '';

UPDATE "product"."StoreBsrSnapshot"
SET "countryCode" = CASE "storeKey"
  WHEN 'A2EUQ1WTGCTBG2' THEN 'CA'
  WHEN 'ATVPDKIKX0DER' THEN 'US'
  WHEN 'A1AM78C64UM0Y8' THEN 'MX'
  WHEN 'A2Q3Y263D00KWC' THEN 'BR'
  WHEN 'A28R8C7NBKEWEA' THEN 'IE'
  WHEN 'A1RKKUPIHCS9HS' THEN 'ES'
  WHEN 'A1F83G8C2ARO7P' THEN 'GB'
  WHEN 'A13V1IB3VIYZZH' THEN 'FR'
  WHEN 'AMEN7PMS3EDWL' THEN 'BE'
  WHEN 'A1805IZSGTT6HS' THEN 'NL'
  WHEN 'A1PA6795UKMFR9' THEN 'DE'
  WHEN 'APJ6JRA9NG5V4' THEN 'IT'
  WHEN 'A2NODRKZP88ZB9' THEN 'SE'
  WHEN 'AE08WJ6YKNBMC' THEN 'ZA'
  WHEN 'A1C3SOZRARQ6R3' THEN 'PL'
  WHEN 'ARBP9OOSHTCHU' THEN 'EG'
  WHEN 'A33AVAJ2PDY3EV' THEN 'TR'
  WHEN 'A17E79C6D8DWNP' THEN 'SA'
  WHEN 'A2VIGQ35RCS4UG' THEN 'AE'
  WHEN 'A21TJRUUN4KGV' THEN 'IN'
  WHEN 'A19VAU5U5O7RUS' THEN 'SG'
  WHEN 'A39IBJ37TRP1C6' THEN 'AU'
  WHEN 'A1VC38T7YXB528' THEN 'JP'
  ELSE "countryCode"
END;

ALTER TABLE "product"."StoreBsrSnapshot" ALTER COLUMN "countryCode" DROP DEFAULT;

CREATE INDEX "StoreBsrSnapshot_asin_country_date" ON "product"."StoreBsrSnapshot"("asin", "countryCode", "capturedAt");
